export const DRAFT_PLAYER = 'DRAFT_PLAYER';
export const LOAD_DRAFT_ORDER = 'LOAD_DRAFT_ORDER';
export const LOAD_DRAFT_PICKS = 'LOAD_DRAFT_PICKS';
export const LOAD_FANTASY_PLAYERS = 'LOAD_FANTASY_PLAYERS';
export const LOAD_FOOTBALL_PLAYERS = 'LOAD_FOOTBALL_PLAYERS';
export const LOAD_MY_LEAGUES = 'LOAD_MY_LEAGUES';
export const LOAD_USER = 'LOAD_USER';
